apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]


  # kubectl create role developer --resource=pods --verb=create,list,get,update,delete --namespace=development
